---
- name: Configure Database Servers
  hosts: db
  become: yes
  roles:
    - db

- name: Configure Web Servers
  hosts: web
  become: yes
  vars:
    web_title: "My Ansible Managed Site"
  roles:
    - web
    - app

- name: Configure Load Balancer
  hosts: loadbalancer
  become: yes
  roles:
    - loadbalancer