---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Configure HAProxy to balance the web servers
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Ensure HAProxy is running
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
